/*
 * File: app/store/Statuses.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Friends.store.Statuses', {
    extend: 'Ext.data.Store',

    requires: [
        'Friends.model.Status'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            api: '/statuses?fields=message',
            storeId: 'feeds',
            model: 'Friends.model.Status',
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    },

    loadFromFb: function(api) {
        var me = this;

        FB.api(api, function(response) {
            me.loadRawData(response);
        });
    },

    load: function() {
        this.loadFromFb('/' + this.userId + this.api);
    },

    setUserId: function(userId) {
        this.userId = userId;
    }

});