/*
 * File: app/view/Friends.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Friends.view.Friends', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.friends',

    title: 'Friends',
    hideHeaders: true,
    store: 'Friends',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'textfield',
                    dock: 'top',
                    id: 'search',
                    emptyText: 'Enter a name to filter...'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    flex: 1,
                    text: 'String'
                }
            ]
        });

        me.callParent(arguments);
    }

});