/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Friends.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Friends.view.Friends',
        'Friends.view.Info'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'friends',
                    id: 'friendsPanel',
                    flex: 1,
                    region: 'center',
                    listeners: {
                        afterrender: {
                            fn: me.onFriendsAfterRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'info',
                    id: 'infoPanel',
                    flex: 5,
                    region: 'east',
                    split: true
                }
            ]
        });

        me.callParent(arguments);
    },

    onFriendsAfterRender: function(abstractcomponent, options) {
        abstractcomponent.setLoading('Loading friends list...');
    }

});